name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ruff
      - name: Lint
        run: ruff check .
      - name: Smoke run (non-interactive)
        run: |
          python - << 'PY'
          import os, sys, subprocess, pty
          # Try to print header and exit quickly by sending 'end'
          cmd = [sys.executable, "main.py"]
          try:
            p = subprocess.Popen(cmd, stdin=subprocess.PIPE, text=True)
            p.communicate("end
", timeout=10)
          except Exception as e:
            print("Smoke run skipped:", e)
          PY
