# .github/workflows/ci.yml
name: CI
permissions:
  contents: write   # allow bot to push auto-fixes

on:
  push:
  pull_request:

jobs:
  lint_and_smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install ruff

      # Auto-fix Python style with Ruff 
      - name: Ruff auto-fix (never fail)
        run: |
          ruff check --fix --exit-zero .
          ruff format .
        continue-on-error: true

      # Commit & push only if fixes were applied
      - name: Commit & push auto-fixes (if any)
        run: |
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "ci: ruff auto-fix"
            git push || true
          fi

      # Report lint, but never fail the build
      - name: Lint report (non-blocking)
        run: ruff check --exit-zero .
        continue-on-error: true

      # Run the game once and exit; never fail CI
      - name: Smoke run (non-blocking)
        run: |
          python - << 'PY'
          import subprocess, sys
          p = subprocess.Popen([sys.executable, "main.py"], stdin=subprocess.PIPE, text=True)
          try:
              p.communicate("end\n", timeout=12)  # send 'end' so your loop exits
          except Exception as e:
              print("Smoke run skipped:", e)
              try: p.kill()
              except Exception: pass
          sys.exit(0)
          PY
      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install ruff bandit pip-audit

      - name: Security (Bandit, non-blocking)
        run: bandit -q -r . || true

      - name: Dependency scan (pip-audit, non-blocking)
        run: pip-audit -q || true

        
