# .github/workflows/tests.yml
name: Tests
on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install
        run: |
          python -m pip install -U pip
          pip install pytest

      - name: Run tests
        run: pytest -q

      
      - name: Smoke run (non-blocking)
        run: python cli.py --auto-end || true
